-- =========================================================================================
-- SCRIPT SQL: Recriação da Tabela observacoes_pratica com Chave Única e Políticas RLS
-- Execute este script no SQL Editor do seu Painel do Supabase
-- =========================================================================================

-- 1. Se a tabela ainda existir em algum estado inconsistente, descarta
DROP TABLE IF EXISTS public.observacoes_pratica CASCADE;

-- 2. Cria a tabela oficial com todos os campos necessários
CREATE TABLE public.observacoes_pratica (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_origem TEXT UNIQUE,                                     -- Identificador único determinístico (ex: 1ANO_1SEM_L2)
  email_cursista TEXT NOT NULL,                             -- E-mail institucional do cursista
  nome_cursista TEXT,
  email_formador TEXT,
  nome_formador TEXT,
  ano_formativo TEXT,
  chamamento TEXT,
  modalidade TEXT,
  componente TEXT,
  tema TEXT,
  observacao_realizada TEXT,
  data_pratica DATE,
  data_observacao DATE,
  data_feedback DATE,
  data_agendamento DATE,
  modalidade_feedback TEXT,
  motivo_devolutiva TEXT,
  link_gravacao_pratica TEXT,
  link_planejamento TEXT,
  link_gravacao_feedback TEXT,
  nivel_planejamento TEXT,
  nivel_pratica TEXT,
  evidencias_planejamento TEXT,
  evidencias_pratica TEXT,
  questionamentos_propositivos TEXT,
  proposicoes_sugestoes TEXT,
  combinados TEXT,
  justificativa_nao_realizada TEXT,
  contexto_justificativa TEXT,
  reflexoes_gerais TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 3. Índices de alta performance para o Dashboard e para o UPSERT
CREATE UNIQUE INDEX IF NOT EXISTS idx_obs_pratica_id_origem ON public.observacoes_pratica (id_origem);
CREATE INDEX IF NOT EXISTS idx_obs_pratica_email_cursista ON public.observacoes_pratica (email_cursista);

-- 4. Habilitar RLS (Row Level Security) e permitir leitura/escrita com anon_key e service_role
ALTER TABLE public.observacoes_pratica ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura total para o dashboard" 
ON public.observacoes_pratica FOR SELECT 
USING (true);

CREATE POLICY "Permitir insercao e atualizacao para scripts" 
ON public.observacoes_pratica FOR ALL 
USING (true) 
WITH CHECK (true);

-- 5. Atualizar o cache de esquema da API do Supabase imediatamente
NOTIFY pgrst, 'reload schema';

-- 6. Verificação final (deve retornar tabela criada vazia)
SELECT count(*) AS total_registros FROM public.observacoes_pratica;
